version: '3'
services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - "18080:80"
    volumes:
      - ./src/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/code/:/var/www/html
  app:
    build: ./containers/php/
    depends_on:
      - db
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./src/code/:/var/www/html
