version: '3'
services:
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - "18080:80"
    volumes:
      - ./src/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/code/:/var/www/html
  app:
    build: ./containers/php/
    depends_on:
      - mysql
    volumes:
      - ./containers/php/php.ini:/usr/local/etc/php/php.ini
      - ./src/code/:/var/www/html
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sunflower
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./containers/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  mssql:
    build: ./containers/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=P@ssw0rd
    volumes: 
      - ./containers/mssql/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgsql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./containers/pgsql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"